AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Este es mi primer YAML 
  para cloudformation en la nube de AWS

Resources:
  MyInstanceEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: "ami-053b0d53c279acc90"
      InstanceType: t2.micro

