AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Este es mi segundo YAML 
  para cloudformation en la nube de AWS

Resources:
  MyInstanceEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: "ami-053b0d53c279acc90"
      KeyName: "keyPrueba"
      InstanceType: t2.micro
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "SSH security group"
      GroupName: "SSH security group"
      VpcId: "vpc-0387a2c81ea5d1966"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

      
